name: Claude Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

jobs:
  claude_review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      repository-projects: write

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: Claude Code Reviewの実行
        uses: anthropic-ai/claude-code-action@v1

  claude_comment_response:
    if: |
      github.event_name == 'issue_comment' && contains(github.event.comment.body, '/claude')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: Claudeコマンドへの応答
        uses: anthropic-ai/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
